### ISSUE TITLE
Polykinded type-aligned sequences

### ISSUE THREAD

**Issue by echatav** [atzeus/type-aligned#15]
Hello, could you loosen the kinds of the different sequences, e.g.

```haskell
data ConsList (c :: k -> k -> *) (x :: k) (y :: k) where
  CNil :: ConsList c x x
  Cons :: c x y -> ConsList c y z -> ConsList c x z
```

Or would you be open to a PR assuming it's possible?

**Comment by treeowl** [comment]
This will presumably require a bump in the minimal GHC bound, or some CPP. Seems reasonable to me, though!

**Comment by echatav** [comment]
:-O I kinda made a [competing library](https://hackage.haskell.org/package/free-categories) with [this type](https://hackage.haskell.org/package/free-categories-0.2.0.2/docs/Control-Category-Free.html#t:Path) since I opened this Issue!

**Comment by treeowl** [comment]
Ooh, another library for me to contribute to! Hopping over!

**Comment by treeowl** [comment]
Oh, but you don't have very many data structures there....

**Comment by echatav** [comment]
> Oh, but you don't have very many data structures there....

Yeah, I'm missing all the sequence stuff which this library is awesome for.

**Comment by treeowl** [comment]
I can try to port some things over. It might help if you added some documentation that's not in category theory language. I have no idea what a quiver is....

**Comment by echatav** [comment]
> I have no idea what a quiver is....
![40CB1D3C-0E96-48C8-910E-060589FA9563](https://user-images.githubusercontent.com/2265940/128121022-ad0810b1-d0fb-482e-a6f6-7f7e442babcd.jpeg)
That one at least is easy but I can see how everything else may be a bit impenetrable….

**Comment by echatav** [comment]
There's some [motivating exposition here](https://github.com/morphismtech/free-categories/blob/master/Announcement.md); if you'd like to discuss further, let's [open an issue there](https://github.com/morphismtech/free-categories/issues).
